# Generated by Django 5.0.2 on 2024-02-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام کنسرت')),
                ('SingerName', models.CharField(max_length=100, verbose_name='نام خواننده')),
                ('length', models.IntegerField(verbose_name='مدت زمان')),
                ('Poster', models.ImageField(upload_to='concertImages/', verbose_name='پوستر')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت',
            },
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('IdNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, verbose_name='نام محل')),
                ('Address', models.CharField(default='تهران-برج میلاد', max_length=500, verbose_name='آدرس ')),
                ('Phone', models.CharField(max_length=11, null=True, verbose_name='تلفن ')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
            ],
            options={
                'verbose_name': 'محل برگزاری',
                'verbose_name_plural': 'محل برگزاری',
            },
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField(verbose_name='زمان برگزاری')),
                ('Seats', models.IntegerField(verbose_name='تعداد صندلی')),
                ('Status', models.IntegerField(choices=[(1, '.فروش بلیط شروع شده است'), (2, '.فروش بلیط تمام شده است'), (3, '.این سانس کنسل شده است'), (4, '.فروش بلیط به زودی شروع خواهد شد')], null=True, verbose_name='وضعیت')),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel', verbose_name='کنسرت')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel', verbose_name='محل برگزاری')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس',
            },
        ),
    ]
