# Generated by Django 5.0.2 on 2024-02-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('ProfileImage', models.ImageField(upload_to='ProfileImages/', verbose_name='عکس')),
                ('Gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketImage', models.ImageField(upload_to='TicketImages/', verbose_name='عکس')),
                ('Name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('Price', models.IntegerField(verbose_name='مبلغ')),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel', verbose_name='کاربر')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
