# Generated by Django 5.0.2 on 2024-03-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0004_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'صندلی', 'verbose_name_plural': 'صندلی'},
        ),
    ]
