# Generated by Django 5.0.2 on 2024-03-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0005_alter_seat_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
